config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("todolist.urls")),
]

todolist/urls.py
from django.urls import path
from . import views

app_name    = "todolist"
urlpatterns = [ 
    path("", views.index, name="index"),
    path("done/<int:pk>/", views.done, name="done"),
    path("todo/", views.todo, name="todo"),
]

todolist/models.py
from django.db import models
from django.utils import timezone


class Todo(models.Model):

    dt          = models.DateTimeField(verbose_name="投稿日時",default=timezone.now)
    deadline    = models.DateField(verbose_name="期日")
    content     = models.CharField(verbose_name="やること", max_length=300)

    done        = models.BooleanField(verbose_name="やった", default=False)

    def __str__(self):
        return self.content

todolist/forms.py
from django import forms
from .models import Todo

import datetime

class TodoForm(forms.ModelForm):
    class Meta:
        model   = Todo
        fields  = [ "deadline","content" ]

class DateSearchForm(forms.Form):

    # バリデーションエラー回避のため、一時的にDateTime型で受け取る。
    start   = forms.DateTimeField()
    end     = forms.DateTimeField()

    # Date型に変換。
    def clean(self):
        cleaned_data = super().clean()
    
        # 月初に設定
        start       = cleaned_data["start"].replace(day=1).date()

        # 最終日を取り出す
        # TIPS:来月の月始めを取り出す(12月であれば+1で、1月になる) それに、1日マイナスする
        end         = (start.replace(month=start.month % 12 + 1, day=1) - datetime.timedelta(days=1))

        cleaned_data["start"]   = start
        cleaned_data["end"]     = end 

        return cleaned_data

todolist/views.py
from django.shortcuts import render, redirect
from django.views import View

from .models import Todo
from .forms import TodoForm,DateSearchForm

from django.utils import timezone 
import datetime

from django.http import JsonResponse


class IndexView(View):
    def get(self, request, *args, **kwargs):

        context             = {}
        context["todos"]    = Todo.objects.order_by("deadline", "dt")

        return render(request, "todolist/index.html", context)

    def post(self, request, *args, **kwargs):

        form    = TodoForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect("todolist:index")

index   = IndexView.as_view()


class DoneView(View):
    def post(self, request, pk, *args, **kwargs):
        todo        = Todo.objects.filter(id=pk).first()
        todo.done   = not todo.done
        todo.save()

        return redirect("todolist:index")

done    = DoneView.as_view()


# 年月を指定して、一致するTodoだけをレスポンスする
class TodoView(View):
    def get(self, request, *args, **kwargs):

        events  = []
        form    = DateSearchForm(request.GET)
    
        date    = timezone.now().date()

        start   = date.replace(day=1)
        end     = date.replace(month=date.month % 12 + 1) - datetime.timedelta(days=1)

        if form.is_valid():
            start   = form.cleaned_data["start"]
            end     = form.cleaned_data["end"]


        todos   = Todo.objects.filter(deadline__gte=start, deadline__lte=end)

        for todo in todos:

            event                       = {}
            event["id"]                 = todo.id
            event["title"]              = f"{todo.content}"
            event["start"]              = todo.deadline
            event["borderColor"]        = "white"

            if todo.done:
                event["backgroundColor"]    = "gray"
            else:
                event["backgroundColor"]    = "deepskyblue"

            events.append(event)

        return JsonResponse(events, safe=False)

todo    = TodoView.as_view()

templates/todolist/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Todoリスト</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.6/index.global.min.js"></script>
    
    {% comment %}
    <script>
        const events =
            [
                        // イベントごとに装飾を施す
                        // https://fullcalendar.io/docs/event-object
                        {% for todo in todos %}
                        {
                                    id:"{{ todo.id }}",
                                    title:"{{ todo.content }}",
                                    start:"{{ todo.deadline|date:'Y-m-d' }}",
                                    backgroundColor: {% if not todo.done %}"deepskyblue"{% else %}"gray"{% endif %}, //進捗状況に応じて色分けできる
                                    borderColor: "white"
                        },
                        {% endfor %}
                ] 
    </script>
    {% endcomment %}

    <script>
        const todo_url  = "{% url 'todolist:todo' %}";
    </script>


    <script src="{% static 'todolist/js/script.js' %}"></script>

</head>
<body>

    <main class="mx-2">
        {# ここが投稿用フォーム #}

        <div class="row mx-0">
            <div class="col-md-6">
                <div id='calendar' style=""></div>
            </div>
            <div class="col-md-6">
                <form method="POST">
                    {% csrf_token %}
                    <input name="deadline" type="text" readonly>
                    <textarea class="form-control" name="content"></textarea>
                    <input type="submit" value="送信">
                </form>

                {# TODO: ここはタブシステムを使って完了と未完を表示切り替えする。 #}
                {# https://noauto-nolife.com/post/css3-tab-system/ #}
                {% for todo in todos %}
                <div id="todo_{{ todo.id }}" class="border">
                    <div>期限: {{ todo.deadline }}</div>
                    <div>やること: {{ todo.content }}</div>
                    <form class="text-right" action="{% url 'todolist:done' todo.id %}" method="post">
                        {% csrf_token %}
                        {% if todo.done %}
                        <input class="btn btn-primary " type="submit" value="完了">
                        {% else %}
                        <input class="btn btn-outline-primary " type="submit" value="やった">
                        {% endif %}
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>


    </main>
</body>
</html>